"""Graph builder - StateGraph supervisor (multi-agent) topology.

Generated by the AIX agent assembler. Do not edit directly; re-run
``python assembler/assemble.py`` to regenerate.

Features: rag
Graph: state_graph (supervisor / multi-agent)
Runtime: gke
"""

from __future__ import annotations

from langchain_core.messages import SystemMessage
from langgraph.graph import END, START, MessagesState, StateGraph
from langgraph.prebuilt import ToolNode, tools_condition

from agent.checkpointing import get_checkpointer
from agent.llm_wrapper import MiddlewareWrappedLLM
from agent.middleware import LoggingMiddleware
from agent.model import amodel
from agent.rag.tools import search_documents_by_query
from config.constants import LLM_MODEL_KEY
from config.prompts import SYSTEM_PROMPT

_TOOLS = [search_documents_by_query]
_SUB_GRAPHS: dict = {}


def route(state: MessagesState) -> str:
    """Choose the next node based on the current conversation state."""
    return END


async def build():
    """Build and return a compiled supervisor StateGraph."""
    llm = await amodel(LLM_MODEL_KEY, model_kwargs={})
    checkpointer = await get_checkpointer()
    llm = MiddlewareWrappedLLM(llm, [LoggingMiddleware()])
    llm_with_tools = llm.bind_tools(_TOOLS) if _TOOLS else llm

    async def call_supervisor(state: MessagesState):
        messages = [SystemMessage(content=SYSTEM_PROMPT)] + list(state["messages"])
        return {"messages": [await llm_with_tools.ainvoke(messages)]}

    graph = StateGraph(MessagesState)
    graph.add_node("supervisor", call_supervisor)
    graph.add_node("tools", ToolNode(_TOOLS))
    graph.add_edge(START, "supervisor")
    graph.add_conditional_edges("supervisor", tools_condition)
    graph.add_edge("tools", "supervisor")
    for name, sub in _SUB_GRAPHS.items():
        graph.add_node(name, sub)
    return graph.compile(checkpointer=checkpointer)
