"""Application lifecycle and initialization.

Generated by the AIX agent assembler. Do not edit directly; re-run
``python assembler/assemble.py`` to regenerate.

Features: rag
"""
from __future__ import annotations

import asyncio
import logging
import os
from contextlib import asynccontextmanager
from pathlib import Path

from fastapi import FastAPI

from agent.factory import GraphFactory
from agent.knowledge import seed_knowledge_base
from agent.rag.initializer import initialize_document_store, initialize_embedding_model
from config.constants import DEBUG_MODE, EPAS_ENV, SAFECHAIN_CONFIG_PATH
from config.env import load_environment
from config.settings import init_settings


@asynccontextmanager
async def lifespan(app: FastAPI):
    """FastAPI lifespan: bootstrap environment, init components, build graph."""
    load_environment()
    os.environ.setdefault("CONFIG_PATH", SAFECHAIN_CONFIG_PATH)
    init_settings()
    if DEBUG_MODE:
        logging.basicConfig(level=logging.DEBUG)
        print(f"Starting up ({EPAS_ENV})")
    await initialize_embedding_model(app)
    await initialize_document_store(app)
    if os.getenv("AUTO_SEED_KNOWLEDGE", "true").lower() in {"true", "1", "yes"}:
        app.state.knowledge_seed = await seed_knowledge_base(
            app, Path(os.getenv("KNOWLEDGE_BASE_PATH", "knowledge"))
        )
    app.state.graph = await GraphFactory.create()
    if DEBUG_MODE:
        print("All components ready")
    yield
    if hasattr(app.state, "embeddings_task"):
        app.state.embeddings_task.cancel()
        try:
            await app.state.embeddings_task
        except asyncio.CancelledError:
            pass
    if hasattr(app.state, "document_store") and hasattr(app.state.document_store, "close"):
        await app.state.document_store.close()
